name: Kaggle Badges

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  create-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Puppeteer browser
        run: npx puppeteer browsers install chrome@131.0.6778.85

      - name: Use Kaggle Badges Action
        uses: spider-man-tm/kaggle-badges@v1.3.0
        with:
          user_name: hutch1221

      - name: push kaggle-badges to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: kaggle-badges
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push kaggle-plates to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: kaggle-plates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
